#-------------------------------
# General Site Settings

#menu:
#- {name: 'Projects', url: ''}
#- {name: 'Blog', url: 'pages/blog.html'}
#- {name: 'About', url: 'pages/about.html'}
#- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: https://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics-ua: #'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'marcelomesmo'

#-------------------------------
# About Section

about: >
  # Personal portfolio

  
contact: >
  # Contact

 
#-------------------------------
# Work Section

games:
- {name: 'Hekura', folder: 'game-1', file: 'games/game-1.html'}
- {name: 'Dark Tarot of Memory', folder: 'game-2', file: 'games/game-2.html'}
- {name: 'Dr. BloodStrike', folder: 'game-3', file: 'games/game-3.html'}
- {name: 'MONSTERS!', folder: 'game-4', file: 'games/game-4.html'}

projects:
- {name: 'Reis', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'MuSSE', folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: 'HEEG', folder: 'proj-3', file: 'projects/proj-3.html'}

profilepic: 'assets/img/profile.png'

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'https://twitter.com/pixuarte'}
- {icon: 'pencil', link: 'https://www.artstation.com/marcelomesmo'}
- {icon: 'github', link: 'https://github.com/marcelomesmo'}
- {icon: 'envelope', link: 'mailto:marcelo.barbosa@ifrn.edu.br'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
